steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/PhilipBessong/wodboxrepo', 'app']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'app'  # Set the working directory to 'app'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:ionic']
    dir: 'app'  # Set the working directory to 'app'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--quiet'
      - '--project=wodbox-407204'
      - '--version=v1'
      - 'app.yaml'
    dir: 'app'  # Set the working directory to 'app'

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
  machineType: 'E2_HIGHCPU_8'
