steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args:
  - 'restore'
  - '--runtime'
  - 'linux-x64'  # Specify a runtime identifier suitable for the build environment

- name: 'gcr.io/cloud-builders/dotnet'
  args:
  - 'build'
  - '-c'
  - 'Release'
  - '--no-restore'
  - '--runtime'
  - 'linux-x64'
