steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args:
  - 'restore'
  - '-r'
  - 'linux-x64'
  - 'wodapi/wodapi.csproj'  # Replace with the actual path to your .csproj file

- name: 'gcr.io/cloud-builders/dotnet'
  args:
  - 'build'
  - '-c'
  - 'Release'
  - '--no-restore'
  - '-r'
  - 'linux-x64'
  - 'wodapi/wodapi.csproj'  # Replace with the actual path to your .csproj file

# Add more steps as needed...
