steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - 'git clone --branch e655a3f3-5842-4f9a-8cec-a48f359ba40f https://github.com/PhilipBessong/wodboxrepo /workspace/wodboxrepo'

- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'cd wodapi && dotnet restore --runtime linux-x64 --source https://api.nuget.org/v3/index.json'

- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'cd wodapi && dotnet build -c Release --no-restore --runtime linux-x64'

