steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - 'git clone --branch main https://github.com/PhilipBessong/wodboxrepo /workspace/wodboxrepo'

- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'cd wodboxrepo && dotnet build -c Release --no-restore'
