// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wodapi.Models;

#nullable disable

namespace wodapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230925152125_secMigrate")]
    partial class secMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wodapi.Models.Exercise", b =>
                {
                    b.Property<int>("exeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("exeId"));

                    b.Property<string>("MobileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exeId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            exeId = 1,
                            MobileUrl = "mobile/WodBox Weighted Step-up.mp4",
                            Name = " Weighted WodBox Step-ups",
                            VideoUrl = "text/41 WodBox Weighted Step-up.mp4"
                        },
                        new
                        {
                            exeId = 2,
                            MobileUrl = "mobile/WodBox Jumps.mp4",
                            Name = "WodBox Jumps",
                            VideoUrl = "text/40 WodBox Jumps.mp4"
                        },
                        new
                        {
                            exeId = 3,
                            MobileUrl = "mobile/WodBox Step Overs.mp4",
                            Name = "WodBox Step Overs",
                            VideoUrl = "text/37 WodBox Step Overs.mp4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
